name: Auto Merge PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' || 
      github.actor == 'OCEANOFANYTHINGOFFICIAL' || 
      github.actor == 'DIPRAGHOSH2006' || 
      github.actor == 'dawidprofo' || 
      github.actor == 'renovate[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        uses: actions/setup-node@v3

      - name: Wait for CI checks to pass
        uses: actions/github-script@v6
        with:
          script: |
            const { github, context } = require('@actions/github');
            const pullRequestSha = context.payload.pull_request.head.sha;
            
            async function checkCI() {
              const { data: checkRuns } = await github.checks.listForRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: pullRequestSha,
              });

              const allChecksPassed = checkRuns.check_runs.every(run => run.conclusion === 'success');
              if (!allChecksPassed) {
                throw new Error('Not all CI checks have passed.');
              }
            }
            
            checkCI().catch(error => {
              console.error(error);
              process.exit(1);
            });

      - name: Automatically merge PRs
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash --message "chore: ${{ github.event.pull_request.title }}" --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
